spring:
  datasource:
    url: jdbc:h2:file:/data/basic
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.dialect.H2Dialect
    hibernate:
      ddl-auto: update